# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: webuimessages_audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'webuimessages_audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import steammessages_base_pb2 as steammessages__base__pb2
import webuimessages_base_pb2 as webuimessages__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19webuimessages_audio.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\">\n\'CAudio_PlaySpeakerTestOnChannel_Request\x12\x13\n\x0b\x63hannel_num\x18\x01 \x01(\x05\";\n(CAudio_PlaySpeakerTestOnChannel_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32~\n\x05\x41udio\x12o\n\x18PlaySpeakerTestOnChannel\x12(.CAudio_PlaySpeakerTestOnChannel_Request\x1a).CAudio_PlaySpeakerTestOnChannel_Response\x1a\x04\x80\x97\"\x01\x42\x05H\x01\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webuimessages_audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001\200\001\001'
  _globals['_AUDIO']._loaded_options = None
  _globals['_AUDIO']._serialized_options = b'\200\227\"\001'
  _globals['_CAUDIO_PLAYSPEAKERTESTONCHANNEL_REQUEST']._serialized_start=81
  _globals['_CAUDIO_PLAYSPEAKERTESTONCHANNEL_REQUEST']._serialized_end=143
  _globals['_CAUDIO_PLAYSPEAKERTESTONCHANNEL_RESPONSE']._serialized_start=145
  _globals['_CAUDIO_PLAYSPEAKERTESTONCHANNEL_RESPONSE']._serialized_end=204
  _globals['_AUDIO']._serialized_start=206
  _globals['_AUDIO']._serialized_end=332
# @@protoc_insertion_point(module_scope)
