# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: webuimessages_screensaver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'webuimessages_screensaver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2
import steammessages_base_pb2 as steammessages__base__pb2
import webuimessages_base_pb2 as webuimessages__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fwebuimessages_screensaver.proto\x1a\x0b\x65nums.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\"%\n#CScreensaver_GetActiveState_Request\"6\n$CScreensaver_GetActiveState_Response\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\">\n,CScreensaver_ActiveStateChanged_Notification\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x32\xcf\x01\n\x0bScreensaver\x12]\n\x0eGetActiveState\x12$.CScreensaver_GetActiveState_Request\x1a%.CScreensaver_GetActiveState_Response\x12[\n\x18NotifyActiveStateChanged\x12-.CScreensaver_ActiveStateChanged_Notification\x1a\x10.WebUINoResponse\x1a\x04\x80\x97\"\x01\x42\x05H\x01\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webuimessages_screensaver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001\200\001\001'
  _globals['_SCREENSAVER']._loaded_options = None
  _globals['_SCREENSAVER']._serialized_options = b'\200\227\"\001'
  _globals['_CSCREENSAVER_GETACTIVESTATE_REQUEST']._serialized_start=100
  _globals['_CSCREENSAVER_GETACTIVESTATE_REQUEST']._serialized_end=137
  _globals['_CSCREENSAVER_GETACTIVESTATE_RESPONSE']._serialized_start=139
  _globals['_CSCREENSAVER_GETACTIVESTATE_RESPONSE']._serialized_end=193
  _globals['_CSCREENSAVER_ACTIVESTATECHANGED_NOTIFICATION']._serialized_start=195
  _globals['_CSCREENSAVER_ACTIVESTATECHANGED_NOTIFICATION']._serialized_end=257
  _globals['_SCREENSAVER']._serialized_start=260
  _globals['_SCREENSAVER']._serialized_end=467
# @@protoc_insertion_point(module_scope)
