# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: webuimessages_user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'webuimessages_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import steammessages_base_pb2 as steammessages__base__pb2
import webuimessages_base_pb2 as webuimessages__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18webuimessages_user.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\"7\n\x1e\x43User_SaveHardwareInfo_Request\x12\x15\n\rfriendly_name\x18\x01 \x01(\t\"<\n\x1f\x43User_SaveHardwareInfo_Response\x12\x19\n\x11saved_hardware_id\x18\x01 \x01(\x04\"$\n\"CUser_GetSavedHardwareInfo_Request\"\x84\x01\n#CUser_GetSavedHardwareInfo_Response\x12\x15\n\rfriendly_name\x18\x01 \x01(\t\x12\x19\n\x11saved_hardware_id\x18\x02 \x01(\x04\x12+\n\x0bsystem_info\x18\x03 \x01(\x0b\x32\x16.UserSystemInformation2\xc6\x01\n\x04User\x12U\n\x10SaveHardwareInfo\x12\x1f.CUser_SaveHardwareInfo_Request\x1a .CUser_SaveHardwareInfo_Response\x12\x61\n\x14GetSavedHardwareInfo\x12#.CUser_GetSavedHardwareInfo_Request\x1a$.CUser_GetSavedHardwareInfo_Response\x1a\x04\x80\x97\"\x02\x42\x05H\x01\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webuimessages_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001\200\001\001'
  _globals['_USER']._loaded_options = None
  _globals['_USER']._serialized_options = b'\200\227\"\002'
  _globals['_CUSER_SAVEHARDWAREINFO_REQUEST']._serialized_start=80
  _globals['_CUSER_SAVEHARDWAREINFO_REQUEST']._serialized_end=135
  _globals['_CUSER_SAVEHARDWAREINFO_RESPONSE']._serialized_start=137
  _globals['_CUSER_SAVEHARDWAREINFO_RESPONSE']._serialized_end=197
  _globals['_CUSER_GETSAVEDHARDWAREINFO_REQUEST']._serialized_start=199
  _globals['_CUSER_GETSAVEDHARDWAREINFO_REQUEST']._serialized_end=235
  _globals['_CUSER_GETSAVEDHARDWAREINFO_RESPONSE']._serialized_start=238
  _globals['_CUSER_GETSAVEDHARDWAREINFO_RESPONSE']._serialized_end=370
  _globals['_USER']._serialized_start=373
  _globals['_USER']._serialized_end=571
# @@protoc_insertion_point(module_scope)
