# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: steammessages_unified_test_steamclient.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'steammessages_unified_test_steamclient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import steammessages_base_pb2 as steammessages__base__pb2
import steammessages_unified_base_steamclient_pb2 as steammessages__unified__base__steamclient__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,steammessages_unified_test_steamclient.proto\x1a\x18steammessages_base.proto\x1a,steammessages_unified_base_steamclient.proto\"5\n CMsgTest_MessageToClient_Request\x12\x11\n\tsome_text\x18\x01 \x01(\t\"6\n!CMsgTest_MessageToClient_Response\x12\x11\n\tsome_text\x18\x01 \x01(\t\"7\n\"CMsgTest_NotifyClient_Notification\x12\x11\n\tsome_text\x18\x01 \x01(\t\"5\n CMsgTest_MessageToServer_Request\x12\x11\n\tsome_text\x18\x01 \x01(\t\"6\n!CMsgTest_MessageToServer_Response\x12\x11\n\tsome_text\x18\x01 \x01(\t\"7\n\"CMsgTest_NotifyServer_Notification\x12\x11\n\tsome_text\x18\x01 \x01(\t\"0\n\x1f\x43MsgTest_TestClientCall_Request\x12\r\n\x05param\x18\x01 \x01(\x05\"2\n CMsgTest_TestClientCall_Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x19\n\x17\x43MsgTest_NoBody_Request\"1\n\x1c\x43MsgTest_CallClient_Response\x12\x11\n\ttestvalue\x18\x01 \x01(\x05\x32\xb3\x01\n\x0fTestSteamClient\x12X\n\x0fMessageToClient\x12!.CMsgTest_MessageToClient_Request\x1a\".CMsgTest_MessageToClient_Response\x12@\n\x0cNotifyClient\x12#.CMsgTest_NotifyClient_Notification\x1a\x0b.NoResponse\x1a\x04\xc0\xb5\x18\x02\x32\x9a\x04\n\x14TestServerFromClient\x12X\n\x0fMessageToServer\x12!.CMsgTest_MessageToServer_Request\x1a\".CMsgTest_MessageToServer_Response\x12@\n\x0cNotifyServer\x12#.CMsgTest_NotifyServer_Notification\x1a\x0b.NoResponse\x12X\n\x11\x43lientCallAuthed1\x12 .CMsgTest_TestClientCall_Request\x1a!.CMsgTest_TestClientCall_Response\x12X\n\x11\x43lientCallAuthed2\x12 .CMsgTest_TestClientCall_Request\x1a!.CMsgTest_TestClientCall_Response\x12X\n\x11\x43lientCallAuthed3\x12 .CMsgTest_TestClientCall_Request\x1a!.CMsgTest_TestClientCall_Response\x12X\n\x11\x43lientCallAuthed4\x12 .CMsgTest_TestClientCall_Request\x1a!.CMsgTest_TestClientCall_Response2^\n\x15TestExternalPrivilege\x12\x45\n\nCallClient\x12\x18.CMsgTest_NoBody_Request\x1a\x1d.CMsgTest_CallClient_ResponseB\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'steammessages_unified_test_steamclient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_TESTSTEAMCLIENT']._loaded_options = None
  _globals['_TESTSTEAMCLIENT']._serialized_options = b'\300\265\030\002'
  _globals['_CMSGTEST_MESSAGETOCLIENT_REQUEST']._serialized_start=120
  _globals['_CMSGTEST_MESSAGETOCLIENT_REQUEST']._serialized_end=173
  _globals['_CMSGTEST_MESSAGETOCLIENT_RESPONSE']._serialized_start=175
  _globals['_CMSGTEST_MESSAGETOCLIENT_RESPONSE']._serialized_end=229
  _globals['_CMSGTEST_NOTIFYCLIENT_NOTIFICATION']._serialized_start=231
  _globals['_CMSGTEST_NOTIFYCLIENT_NOTIFICATION']._serialized_end=286
  _globals['_CMSGTEST_MESSAGETOSERVER_REQUEST']._serialized_start=288
  _globals['_CMSGTEST_MESSAGETOSERVER_REQUEST']._serialized_end=341
  _globals['_CMSGTEST_MESSAGETOSERVER_RESPONSE']._serialized_start=343
  _globals['_CMSGTEST_MESSAGETOSERVER_RESPONSE']._serialized_end=397
  _globals['_CMSGTEST_NOTIFYSERVER_NOTIFICATION']._serialized_start=399
  _globals['_CMSGTEST_NOTIFYSERVER_NOTIFICATION']._serialized_end=454
  _globals['_CMSGTEST_TESTCLIENTCALL_REQUEST']._serialized_start=456
  _globals['_CMSGTEST_TESTCLIENTCALL_REQUEST']._serialized_end=504
  _globals['_CMSGTEST_TESTCLIENTCALL_RESPONSE']._serialized_start=506
  _globals['_CMSGTEST_TESTCLIENTCALL_RESPONSE']._serialized_end=556
  _globals['_CMSGTEST_NOBODY_REQUEST']._serialized_start=558
  _globals['_CMSGTEST_NOBODY_REQUEST']._serialized_end=583
  _globals['_CMSGTEST_CALLCLIENT_RESPONSE']._serialized_start=585
  _globals['_CMSGTEST_CALLCLIENT_RESPONSE']._serialized_end=634
  _globals['_TESTSTEAMCLIENT']._serialized_start=637
  _globals['_TESTSTEAMCLIENT']._serialized_end=816
  _globals['_TESTSERVERFROMCLIENT']._serialized_start=819
  _globals['_TESTSERVERFROMCLIENT']._serialized_end=1357
  _globals['_TESTEXTERNALPRIVILEGE']._serialized_start=1359
  _globals['_TESTEXTERNALPRIVILEGE']._serialized_end=1453
# @@protoc_insertion_point(module_scope)
